# Copyright 2024 3WEBS LLC
# SPDX-License-Identifier: GPL-3.0-or-later
# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

default: true
