# Copyright 2024 3WEBS LLC
# SPDX-License-Identifier: GPL-3.0-or-later

name: Continuous Integration

on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    markdownlint:
        name: 🖋️ Markdownlint
        runs-on: ubuntu-latest
        steps:
          - name: 📦 Checkout Repository
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
            with:
                fetch-depth: 2
          - name: 🟰 Detect Changed Files
            uses: tj-actions/changed-files@20576b4b9ed46d41e2d45a2256e5e2316dde6834 # v43.0.1
            id: changed-files
            with:
              files: '**/*.md'
              separator: ","
          - name: 🖋️ Markdownlint
            uses: DavidAnson/markdownlint-cli2-action@510b996878fc0d1a46c8a04ec86b06dbfba09de7  # v15.0.0
            if: steps.changed-files.outcome == 'success'
            with:
              config: .markdownlint.yml
              globs: ${{ steps.changed-files.outputs.all_changed_files }}
    reuse:
        name: 📝 REUSE
        runs-on: ubuntu-latest
        steps:
          - name: 📦 Checkout Repository
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
            with:
                fetch-depth: 2
          - name: 🟰 Detect Changed Files
            uses: tj-actions/changed-files@20576b4b9ed46d41e2d45a2256e5e2316dde6834 # v43.0.1
            id: changed-files
            with:
              files: '**/*'
              separator: "|"
          - name: 🗑️ Delete Unchanged Files
            run: |
              shopt -s extglob
              rm -rf !(${{ steps.changed-files.outputs.all_changed_files }}|.reuse|LICENSES)
          - name: 📝 REUSE Compliance Check
            uses: fsfe/reuse-action@a46482ca367aef4454a87620aa37c2be4b2f8106  # v3.0.0
