# Copyright 2024 3WEBS LLC
# SPDX-License-Identifier: GPL-3.0-or-later

name: Continuous Integration

on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    markdownlint:
        name: 🖋️ Markdownlint
        runs-on: ubuntu-latest
        steps:
          - name: 📦 Checkout Repository
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
            with:
                fetch-depth: 2
          - name: 🟰 Detect Changed Files
            uses: tj-actions/changed-files@635f118699dd888d737c15018cd30aff2e0274f8 # v44.0.1
            id: changed-files
            with:
              files: '**/*.md'
              separator: ","
          - name: 🖋️ Markdownlint
            uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16.0.0
            if: steps.changed-files.outcome == 'success' && steps.changed-files.outputs.all_changed_files != ''
            with:
              separator: ","
              config: .markdownlint.yml
              globs: ${{ steps.changed-files.outputs.all_changed_files }}
    reuse:
        name: 📝 REUSE
        runs-on: ubuntu-latest
        steps:
          - name: 📦 Checkout Repository
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
            with:
                fetch-depth: 2
          - name: 🟰 Detect Changed Files
            uses: tj-actions/changed-files@635f118699dd888d737c15018cd30aff2e0274f8 # v44.0.1
            id: changed-files
            with:
              files: '**/*'
              separator: "|"
          - name: 🗑️ Delete Unchanged Files
            run: |
              shopt -s extglob
              rm -rf !(${{ steps.changed-files.outputs.all_changed_files }}|.reuse|LICENSES)
          - name: 📝 REUSE Compliance Check
            uses: fsfe/reuse-action@a46482ca367aef4454a87620aa37c2be4b2f8106  # v3.0.0
